### ISSUE TITLE
생일페이지 생성 시 포토방명록&tmi 페이지 state 관련 문제

### ISSUE THREAD

**Issue by simeunseo** [Piro17-Project-Birthday/Piro17-Project-Birthday#17]
지금 시점에서 9월 12일로 생일 페이지를 만들어봤는데,
포토방명록이랑 tmi페이지의 state가 activate로 됨!
deactivate되도록 수정 필요할 듯 함!!
근데 어차피 비활성화된 생일 페이지의 포토방명록과 tmi페이지를 들어갈 방법은 url에 직접 치는 방법말고는 없어서,
심각한 문제는 아니나... 어쨌든 state필드를 만들어놨으니 올바른 처리가 필요할듯함!

**Comment by Yeonseo-Jo** [comment]
해당 부분 수정 완료 했어!
보니까 생일이 아직 안지나서 올해 생일 페이지가 생성될 때 state 처리 구분을 안해놨더라궁
또 오류 찾으면 이슈 남겨줘 고마어!

**Comment by Yeonseo-Jo** [comment]
해당 부분 수정 완료 했어!
보니까 생일이 아직 안지나서 올해 생일 페이지가 생성될 때 state 처리 구분을 안해놨더라궁
또 오류 찾으면 이슈 남겨줘 고마어!
