### ISSUE TITLE
createBirthdayPage에서 이름 필수입력

### ISSUE THREAD

**Issue by simeunseo** [Piro17-Project-Birthday/Piro17-Project-Birthday#19]
생일과 케이크는 입력을 안하고 제출을 누르면 입력해달라고 뜨는데, 이름은 입력하지 않아도 그냥 제출이 되어서 이름이 None으로 뜨는 문제가 발생함. 세가지 필드 모두 null=True, blank=True 로 되어있는데 왜 이름만 그냥 제출되는지 의문...
이에 대해 이름도 입력을 안하면 제출이 안되도록 수정이 필요함!!!

**Comment by Yeonseo-Jo** [comment]
create_birthday_page.html에 이름 넣는 칸만 required=""이 없어서 발생한 문제로 보임. 수정완료!
