### ISSUE TITLE
로그인 리다이렉트 관련

### ISSUE THREAD

**Issue by simeunseo** [Piro17-Project-Birthday/Piro17-Project-Birthday#20]
1. 로그인 안한상태 -> 사이드바에서 생일 페이지 만들기 누름 -> createBirthdayPage후에 내 페이지로 가야하는데 메인으로 redirect됨
2. 발견할때마다 추가하겠음

**Comment by Yeonseo-Jo** [comment]
사이드바에서 생일 페이지 만들기가 없어졌으므로
편의를 위해 로그인 한 유저가 마이페이지에 들어갔을 때 
생일 페이지가 아직 생성되지 않았다면 생일 페이지 생성하기로 갈 수 있는 링크를 추가해주면 좋을것 같음
