### ISSUE TITLE
처음 로그인 시 디폴트 full_name관련 이슈

### ISSUE THREAD

**Issue by simeunseo** [Piro17-Project-Birthday/Piro17-Project-Birthday#21]
full_name이 비워져있는게 디폴트로 되어있어서, 사용자가 자기의 이름을 정하기 전에는 이름을 표시해줄 수가 없는 문제 발생

**Comment by Yeonseo-Jo** [comment]
full_name 필드를 없애고 username 필드로 받아오게 수정 완료
그럼 생일 페이지 만들기 전에는 user로 뜨고 생일 페이지에서 자기의 이름 정한 후에는 정한 이름으로 표시됨
