### ISSUE TITLE
포토방명록 - 포토방명록 남기기 버튼 css 깨짐

### ISSUE THREAD

**Issue by Yeonseo-Jo** [Piro17-Project-Birthday/Piro17-Project-Birthday#22]
![image](https://user-images.githubusercontent.com/77691829/185092747-2e087b5e-cd90-49d4-9b58-a8e4f36ab488.png)

모바일 사이즈 지정 안할 시 포토 방명록 포토 방명록 버튼이 화면 사이즈 넘어서까지 생김
일부로 넘치게 한건강,,?

**Comment by simeunseo** [comment]
수정완!
